### ISSUE TITLE
Share text change/enhancement

### ISSUE THREAD

**Issue by hrishinene** [kedarmhaswade/vardaL#14]
1. Provide url: www.shabdak.com in the shared text
2. <Feedback> One suggestion from me.. can you add a # each one? So when you share your results,  it says, for example" Shabdak 200"

**Comment by kedarmhaswade** [comment]
Thank you for reporting this.

Isn't 2) already happening? We have: 

`शब्दक <the number of days since epoch (Jan 1, 2022)> <#guesses/#max-guesses-allowed>`

**Comment by kedarmhaswade** [comment]
Closed.
